game_title: Memory Game
background_color: !!python/tuple [ 255, 255, 255 ]
back_color_card: !!python/tuple [ 0, 0, 205 ]
front_color_card: !!python/tuple [ 173,216,230 ]
board_size: 6
tile_size: 150
test_color: !!python/tuple [ 255, 255, 205 ]